### ISSUE TITLE
jsportal doc broken, please fix asap

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jumpscale_portal8#123]
https://gig.gitbooks.io/jumpscale-portal8/content/Macros/Macros.html

there was lots more info, what happened

e.g.
- all macro included & how to use them, all of this info is gone

looks like we are going backwards again

**Comment by yveskerwyn** [comment]
@rkhamis I just fixed the TOC, bringing back all the Macros sections, not sure whether I'm doing double work here since (as I just discover) you set the state to verification... I committed directly into 8.1.0_cleanup, as requested by @despiegk in a separate email

**Comment by yveskerwyn** [comment]
@rkhamis sorry I just see that you already did the same and committed into master instead of 8.1.0_cleanup, not sure whether this will give conflicts
