### ISSUE TITLE
Archived blueprint info can't be retrieved

### ISSUE THREAD

**Issue by alichaddad** [Jumpscale/jumpscale_portal8#148]
Having archived blueprints in your repo will produce following error:
```
"404 Not Found\nNo blueprint found with this name '03_Apr_2017_14_22_36.yaml'"
```

**Comment by rkhamis** [comment]
@alichaddad see: https://github.com/Jumpscale/jumpscale_core8/blob/8.2.0/lib/JumpScale/baselib/atyourservice81/server/ays_api.py#L297

**Comment by alichaddad** [comment]
Fixed in https://github.com/Jumpscale/jumpscale_core8/commit/c56b3ee4d6192aa2f5ac0a2bd7094dbe59614617
