### ISSUE TITLE
Clean up of portal

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/jumpscale_portal8#149]
- Drop `system_atyourservice` actor
- add AYS client to portal server with `self.ays_api = j.clients.atyourservice.get(<cfg>).api.ays`
- Reference client in all macros with `j.apps.portal.active.ays_api.<method>` directly.
- Clean up all unused layers in between

**Comment by xmonader** [comment]
Implemented in https://github.com/Jumpscale/jumpscale_portal8/commit/032b7a792bfc2e8634d62f5109ba596e4d6a546b
