### ISSUE TITLE
Portal server space detection loops needlessly

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/jumpscale_portal8#26]
(only on first run)

**Comment by despiegk** [comment]
@rkhamis can we fix it easily?

**Comment by rkhamis** [comment]
I'll investigate and see

**Comment by rkhamis** [comment]
Fixed by https://github.com/Jumpscale/jumpscale_core8/commit/be0d518270a958c25cef6a12660adc1180f3360b
