### ISSUE TITLE
pymongo latest version issue

### ISSUE THREAD

**Issue by ashraffouda** [Jumpscale/jumpscale_portal8#47]
portal.install() installs the latest version of pymongo and this is not working with the current mongoengine
"
mongoengine.connection.ConnectionError: Cannot connect to database jumpscale_system 
"

it works only with pymongo==2.8

**Comment by rkhamis** [comment]
we're working with pymongo==3.2.1 and mongoengine==0.10.6
I verified that installing mongoengine with pip3 on a clean system installs the correct version.
@ashraffouda Could you verify that your system was clean?

**Comment by ashraffouda** [comment]
tried it on a clean system and it worked

**Comment by rkhamis** [comment]
It should upgrade in all cases.

**Comment by ashraffouda** [comment]
https://github.com/Jumpscale/jumpscale_core8/pull/161
