### ISSUE TITLE
Failing to install portal

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/jumpscale_portal8#51]
After installing JS8 on a fresh machine, tried to install the portal on vm-189 on be-scale-3 (https://be-scale-3.demo.greenitglobe.com/CBGrid/Virtual%20Machine?id=189)

Executing:
j.tools.cuisine.local.apps.portal.install()

Result:
[Tue26 15:29] - ...lib/JumpScale/tools/actions/Action.py:513  - INFO     -   * run                 : pip3 install --upgrade pip
E:sudo: unable to resolve host vm-189
E:Traceback (most recent call last):
E:File "/usr/local/bin/pip3", line 11, in <module>
E:sys.exit(main())
E:File "/usr/local/lib/python3.5/dist-packages/pip/__init__.py", line 215, in main
E:locale.setlocale(locale.LC_ALL, '')
E:File "/usr/lib/python3.5/locale.py", line 595, in setlocale
E:return _setlocale(category, locale)
E:locale.Error: unsupported locale setting

*ERROR***********************************************************************************
action: run                  runid:localhost            (ERROR)
    CuisineCore.run.pip3 install --upgrade pip|
    path: /opt/jumpscale8/lib/JumpScale/tools/cuisine/CuisineCore.py
DOC:
    @param profile, execute the bash profile first
ERROR:
    could not execute echo  | sudo -S bash -c "pip3 install --upgrade pip",OUT:
    STDERR:
    sudo: unable to resolve host vm-189
    Traceback (most recent call last):
      File "/usr/local/bin/pip3", line 11, in <module>
        sys.exit(main())
      File "/usr/local/lib/python3.5/dist-packages/pip/__init__.py", line 215, in main
        locale.setlocale(locale.LC_ALL, '')
      File "/usr/lib/python3.5/locale.py", line 595, in setlocale
        return _setlocale(category, locale)
    locale.Error: unsupported locale setting
[Tue26 15:29] - ...lib/JumpScale/tools/actions/Action.py:749  - ERROR    -

******************************************************************************************

[Tue26 15:29] - ...lib/JumpScale/tools/actions/Action.py:621  - ERROR    - error in action: action: run                  runid:localhost       (ERROR)
    pip3 install --upgrade pip

An exception has occurred, use %tb to see the full traceback.

SystemExit: 1

When trying: root@vm-189:/tmp# pip3 install --upgrade pip

  File "/usr/local/bin/pip3", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/pip/__init__.py", line 215, in main
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python3.5/locale.py", line 595, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

Bug?

Thanks for your help

**Comment by abdulrahmantkhalifa** [comment]
Cannot reproduce error, maybe method of installation of jumpscale is different, what method was used ?
but either way the portal requires a mongodb instance to connect to , either 
install on the vm through : 
`j.tools.cuisine.local.apps.mongo.build()`
and then run the portal install command 
or 

connect to
running instance on the network while installing  through : `j.toolls.cuisine.apps.portal.install(mongodbip="", mongoport="")`

**Comment by yveskerwyn** [comment]
Very easy to reproduce @abdulrahmantkhalifa :
- Start from fresh VM on be-scale-3
- Follow the documentation to install JS8: https://gig.gitbooks.io/jumpscale8/content/GettingStarted/Install.html
- Follow the documentation to install the Portal: https://gig.gitbooks.io/jumpscale8/content/Portal/Install.html

Thanks for updating the documentation

That being said, retried on my existing VM:
j.tools.cuisine.local.apps.mongodb.build()
j.tools.cuisine.local.apps.portal.install()

Exists with error:

Traceback (most recent call last):
  File "/tmp/actions/localhost/changeEve.py", line 25, in changeEve
    raise j.exceptions.RuntimeError("Cannot find:%s, to convert to python 3" % path)
OurExceptions.RuntimeError: ERROR: Cannot find:/usr/local/lib/python3.5/dist-packages

STDERR:
sudo: unable to resolve host vm-189/eve_docs/config.py, to convert to python 3 ((type:runtime.error)
[Thu28 09:13] - ...lib/JumpScale/tools/actions/Action.py:749  - ERROR    -

******************************************************************************************

[Thu28 09:13] - ...lib/JumpScale/tools/actions/Action.py:621  - ERROR    - error in action: action: changeEve            runid:localhost       (ERROR)


An exception has occurred, use %tb to see the full traceback.

SystemExit: 1

**Comment by abdulrahmantkhalifa** [comment]
k so this is a current issue being fixed , if u need jumpscale on the machine it can be manually fixed by editing 
the /etc/hosts file to have :
`127.0.0.1 localhost localhost.localdomain <your machine name usually vm-number >`

**Comment by yveskerwyn** [comment]
@abdulrahmantkhalifa, after updating /etc/hosts and re-running the JS8 installation, still got an error, see https://github.com/Jumpscale/jumpscale_core8/issues/208 

Please also update the [documentation](https://gig.gitbooks.io/jumpscale8/content/Portal/Install.html):

j.tools.cuisine.local.apps.mongo.build() -> j.tools.cuisine.local.apps.mongodb.build()
j.tools.cuisine.local.portal.install() -> j.tools.cuisine.local.apps.portal.install()

**Comment by abdulrahmantkhalifa** [comment]
adjusted for both   1510 and 1604 . FIXED , https://github.com/Jumpscale/dockers,

**Comment by xmonader** [comment]
Is that still an issue?

**Comment by yveskerwyn** [comment]
No solved now
