### ISSUE TITLE
Login macro should not try to look for oauth_client service instance

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/jumpscale_portal8#79]
Currently the [login macro](https://github.com/Jumpscale/jumpscale_portal8/tree/master/apps/portalbase/macros/page/login) uses `j.application.getAppInstanceHRDs('oauth_client')` to look after `oauth_client` service instance.

In JS8 we don't use services like that to configure the portal.  The macro should be refactor to use the config file of the portal directly and not look for services instance.

**Comment by rkhamis** [comment]
Done, but needs some css magic. Reassigned to @samaradel 

![css](https://cloud.githubusercontent.com/assets/8425762/20744760/737cddb6-b6e6-11e6-8ef7-0011cdec6bc8.jpg)
