### ISSUE TITLE
AYS81: install blueprint fails

### ISSUE THREAD

**Issue by khaledkbadr** [Jumpscale/jumpscale_portal8#89]

**Comment by rkhamis** [comment]
That doesn't say much. Error? Scenario? How do we reproduce it?

**Comment by khaledkbadr** [comment]
- First it was some attribution error and `fixed in` [https://github.com/Jumpscale/jumpscale_portal8/commit/868a0a154651d5dc46e0654c7b9ce57f6269f34c](url)

Then using `ays.runCreate` since `ays.runGet` is deprecated requires different arguments and looks like some design changing were required.
