### ISSUE TITLE
error on api on my mac

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jumpscale_portal8#92]
![image](https://cloud.githubusercontent.com/assets/6021844/19877451/d2415426-9ff8-11e6-915b-cd87f1c0d1a6.png)

**Comment by abdulrahmantkhalifa** [comment]
this error occurs if not logged in using the itsyou.online oauth as no jwt is available , if want to bypass please add the ``` param.cfg.production = False ``` line to the portal configuration file located at  /JS8/optvar/cfg/portals/main/config.hrd on OSX or /optvar/cfg/portals/main/config.hrd on PCs
