### ISSUE TITLE
explore spaces & spaces overview is not aligned?

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jumpscale_portal8#96]
![image](https://cloud.githubusercontent.com/assets/6021844/19877516/462bb462-9ff9-11e6-84bb-835ca23fffc4.png)

**Comment by despiegk** [comment]
1 in spaces overview, 3 in explore?

**Comment by khaledkbadr** [comment]
Test spaces are hidden spaces. There's no overview for them.
